import { factors, Factor } from './data';
export const ACTION_SCORE = { LOVE:88, UP:62, DOWN:38, HARD_PASS:12 } as const;
export type Action = keyof typeof ACTION_SCORE;
export function cardDeck(): { id:string; factor:Factor; side:'A'|'B' }[] {
 const out:{id:string; factor:Factor; side:'A'|'B'}[]=[]; factors.forEach(f=>{out.push({id:`V-${f}-A`,factor:f,side:'A'}); out.push({id:`V-${f}-B`,factor:f,side:'B'});});
 return out;
}
export function adaptiveDeck(max=14) { const result = factors.map(factor => ({ id: `V-${factor}-A`, factor, side: 'A' as const })); return result.slice(0, Math.max(0, max)); }
export function vibeName(scores:Partial<Record<Factor,number>>) { const first=factors.reduce((a,b)=>Math.abs((scores[a]??50)-50)>=Math.abs((scores[b]??50)-50)?a:b); const remaining=factors.filter(f=>f!==first).map(f=>[f,Math.abs((scores[f]??50)-50)] as const).filter(([,d])=>d>=25 && d>=Math.abs((scores[first]??50)-50)-15).sort((a,b)=>b[1]-a[1]); const second=remaining[0]?.[0]; const words:Record<Factor,[string,string,string,string]>={ENRG:['Low-Key','Slow-Burner','Peak','Climber'],AFFIL:['Mingling','Mingler','Inner-Circle','Insider'],CROWD:['Quiet','Quiet-One','Big-Room','Crowd-Chaser'],TALK:['Loud','Noise-Seeker','Talking','Table-Talker'],ROAM:['Settled','Settler','Nomad','Nomad'],MOVE:['Seated','Sitter','Moving','Floor-Filler'],GAMES:['No-Games','Lounger','Arcade','Score-Keeper']}; const pole=(f:Factor)=>(scores[f]??50)>=50?2:0; if(!second){ const single:Record<Factor,[string,string]>={ENRG:['Slow Burner','Night Climber'],AFFIL:['Room Worker','Inner Circle'],CROWD:['Quiet One','Crowd Chaser'],TALK:['Noise Seeker','Table Talker'],ROAM:['Settler','Nomad'],MOVE:['Sitter','Floor Filler'],GAMES:['Lounger','Score Keeper']}; return single[first][pole(first)/2]; } return `${words[first][pole(first)]} ${words[second][pole(second)+1]}`; }
export function createPlan(scores:Partial<Record<Factor,number>>) { const energy=scores.ENRG??62; return { style: energy>=70?'Could Go Late':'Settle Then Roam', stops: energy>=70?3:2, duration: energy>=70?'8:30 PM – 12:30 AM':'8:30 PM – 11:30 PM' }; }
