import React, { useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors, radius } from './theme';
import { FeatureMode, useApp } from './store';

const content: Record<FeatureMode, { eyebrow: string; title: string; body: string; action: string; next?: FeatureMode; icon: keyof typeof Ionicons.glyphMap }> = {
  venue:{eyebrow:'VENUE DETAIL',title:'Sidecar, GK-2',body:'Buzzy, easy to settle into · Greater Kailash II. Venue media, review notes, pinboard, and preference fit are kept together here.',action:'Add to plan',next:'activePlan',icon:'location-outline'},
  activePlan:{eyebrow:'PERSONAL PLAN',title:'Settle Then Roam',body:'Friday · 8:30 PM – 12:30 AM. Three stops, travel time, approximate arrival windows, and the reason each stop made the cut.',action:'Lock plan',next:'arrival',icon:'map-outline'},
  arrival:{eyebrow:'ACTIVE PLAN',title:'You have arrived',body:'Location sharing is off by default. Arrival is a private state for your plan, not an exact location signal to other people.',action:'End plan',next:'feedback',icon:'flag-outline'},
  feedback:{eyebrow:'STOP FEEDBACK',title:'How did this stop feel?',body:'Rate the room, the conversation, and whether it delivered what the plan promised. Feedback improves venue confidence.',action:'Save feedback',next:'activePlan',icon:'star-outline'},
  hostRoom:{eyebrow:'HOST A ROOM',title:'Give the night a reason',body:'Add co-hosts, choose a room plan, set visibility, and publish. Exact locations stay hidden until the plan consent state allows them.',action:'Add co-hosts',next:'joinRequests',icon:'people-outline'},
  joinRequests:{eyebrow:'JOIN REQUESTS',title:'People who want in',body:'Review requests, see compatibility bands, and accept people without exposing anyone’s exact location.',action:'Open capsule',next:'capsule',icon:'person-add-outline'},
  capsule:{eyebrow:'CAPSULE',title:'A smaller circle inside the room',body:'Members approve before joining. The capsule can be invite-only, friends-only, or opened to the room.',action:'Approve member',next:'chat',icon:'lock-open-outline'},
  notifications:{eyebrow:'NOTIFICATIONS',title:'Stay in the loop',body:'Room requests, plan changes, approvals, and support updates live here. No silent social state changes.',action:'Open inbox',next:'inbox',icon:'notifications-outline'},
  inbox:{eyebrow:'INBOX',title:'Your conversations',body:'Direct messages and group conversations stay separate from the plan. Unread state is explicit.',action:'Open group chat',next:'chat',icon:'mail-outline'},
  chat:{eyebrow:'GROUP CHAT',title:'Friday room',body:'Talk through arrival, plan edits, and the next stop. The demo uses local seeded messages and keeps private content scoped.',action:'View active plan',next:'activePlan',icon:'chatbubbles-outline'},
  visitor:{eyebrow:'VISITOR PROFILE',title:'Someone from the room',body:'See shared vibe context, mutual rooms, and safety controls. No exact location or unrestricted private content is shown.',action:'Report or block',next:'report',icon:'person-outline'},
  editProfile:{eyebrow:'EDIT PROFILE',title:'Keep it current',body:'Update your name, bio, pronouns, photo, preferences, and privacy choices. Vibe history remains immutable per session.',action:'Save profile',next:'history',icon:'create-outline'},
  history:{eyebrow:'VIBE HISTORY',title:'Your nights have a shape',body:'Review frozen daily names, preference badges, and past plans without rewriting history when the population centre changes.',action:'Open past plans',next:'activePlan',icon:'time-outline'},
  privacy:{eyebrow:'PRIVACY & SAFETY',title:'You choose what is shared',body:'Location is off by default. Presence is approximate. Per-plan consent, report, block, and data contribution controls are visible.',action:'Open settings',next:'settings',icon:'shield-checkmark-outline'},
  settings:{eyebrow:'SETTINGS',title:'Make SHUFFL yours',body:'Demo mode, notifications, privacy, support, account, and accessibility preferences are all reachable from one place.',action:'Privacy & safety',next:'privacy',icon:'settings-outline'},
  report:{eyebrow:'SAFETY',title:'Report or block',body:'Choose a reason, block immediately if needed, and send a report for review. The user is not notified of the report details.',action:'Send report',next:'settings',icon:'flag-outline'},
  support:{eyebrow:'SUPPORT',title:'Need a hand?',body:'Account help, safety questions, and plan issues are routed to a clear support state instead of dead-ending.',action:'Back to settings',next:'settings',icon:'help-circle-outline'},
};

function FeatureButton({ label, onPress, secondary = false }: { label: string; onPress: () => void; secondary?: boolean }) { return <Pressable onPress={onPress} style={secondary ? styles.secondary : styles.primary}><Text style={secondary ? styles.secondaryText : styles.primaryText}>{label}</Text></Pressable>; }
function FeatureHeader({ label, onBack }: { label: string; onBack: () => void }) { return <View style={styles.header}><Pressable onPress={onBack} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.text}/></Pressable><Text style={styles.headerLabel}>{label}</Text><Ionicons name="sparkles-outline" size={22} color={colors.mint}/></View>; }
function HostRoomScreen() { const { room, plan, set } = useApp(); const [soloWarning, setSoloWarning] = useState(false); const addCohost = () => set({ room: { ...room, cohosts: ['Bela'], members: ['Aarav', 'Bela'] } }); const createPlan = () => { if (!room.cohosts.length && !soloWarning) return setSoloWarning(true); set({ plan: { ...plan, exists: true, locked: false } }); setSoloWarning(false); }; const host = () => { if (!plan.exists) return; if (!room.cohosts.length && !soloWarning) return setSoloWarning(true); set({ room: { ...room, public: true }, plan: { ...plan, locked: true } }); setSoloWarning(false); }; return <SafeAreaView style={styles.safe}><FeatureHeader label="HOST A ROOM" onBack={() => set({ screen: 'control' })}/><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>ROOM SETUP</Text><Text style={styles.title}>{room.name}</Text><Text style={styles.body}>{room.public ? 'Room is public. The plan and chemistry are now frozen for everyone who joins.' : 'Build the room privately, make the plan, then host it when the room is ready.'}</Text><View style={styles.routeList}>{room.members.map(member => <View key={member} style={styles.route}><Text style={styles.routeText}>{member} · today’s vibe</Text><Text style={styles.secondaryText}>{member === 'Aarav' ? 'HOST' : 'CO-HOST'}</Text></View>)}</View>{!room.public && !room.cohosts.length && <FeatureButton label="Add a co-host" onPress={addCohost}/>} {!room.public && !plan.exists && <FeatureButton label="Create plan" onPress={createPlan} secondary={!!room.cohosts.length}/>} {soloWarning && <View style={styles.route}><Text style={styles.body}>This is a solo plan. Continue with just you?</Text><FeatureButton label="Continue" onPress={createPlan}/></View>} {plan.exists && <View style={styles.routeList}><Text style={styles.eyebrow}>{plan.style} · {plan.locked ? 'LOCKED' : 'PRIVATE DRAFT'}</Text>{plan.stops.map((stop, index) => <View key={stop} style={styles.route}><Text style={styles.routeText}>{index + 1}. {stop}</Text></View>)}</View>} {plan.exists && !room.public && <FeatureButton label="Host room" onPress={host}/>} {room.public && <FeatureButton label="Open join requests" onPress={() => set({ screen: 'feature', featureMode: 'joinRequests' })} secondary/>} {plan.exists && <FeatureButton label="View plan" onPress={() => set({ screen: 'feature', featureMode: 'activePlan' })} secondary/>}</ScrollView></SafeAreaView>; }
function ActivePlanScreen() { const { room, plan, set } = useApp(); return <SafeAreaView style={styles.safe}><FeatureHeader label="ACTIVE PLAN" onBack={() => set({ screen: 'control' })}/><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>{room.public ? 'HOSTED PLAN' : 'PRIVATE PLAN'}</Text><Text style={styles.title}>{plan.style}</Text><Text style={styles.body}>{room.public ? 'This plan is frozen because people joined on the promise of this night.' : 'Refresh is available while the room is private. Locking freezes the night for everyone.'}</Text>{plan.stops.map((stop, index) => <View key={stop} style={styles.route}><Text style={styles.routeText}>{index + 1}. {stop}</Text><Text style={styles.secondaryText}>{index === 0 ? 'SETTLE' : 'ROAM'}</Text></View>)} {!plan.locked && <FeatureButton label="Lock plan" onPress={() => set({ plan: { ...plan, locked: true } })}/>} {!plan.locked && !room.public && <FeatureButton label="Refresh private draft" onPress={() => set({ plan: { ...plan, style: plan.style === 'Settle Then Roam' ? 'Could Go Late' : 'Settle Then Roam' } })} secondary/>}<FeatureButton label="Mark arrival" onPress={() => set({ screen: 'feature', featureMode: 'arrival' })} secondary/></ScrollView></SafeAreaView>; }
function JoinRequestsScreen() { const { room, set } = useApp(); return <SafeAreaView style={styles.safe}><FeatureHeader label="JOIN REQUESTS" onBack={() => set({ screen: 'feature', featureMode: 'hostRoom' })}/><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>ROOM IS PUBLIC</Text><Text style={styles.title}>People who want in</Text><Text style={styles.body}>Requests are grouped by plan fit. Accepting a request re-runs the room blend; the hosted plan itself does not change.</Text>{room.requests.filter(request => !room.accepted.includes(request)).map(request => <View key={request} style={styles.route}><View><Text style={styles.routeText}>{request}</Text><Text style={styles.secondaryText}>Strong match · plan fit 82%</Text></View><View style={{ flexDirection: 'row', gap: 8 }}><Pressable onPress={() => set({ room: { ...room, accepted: [...room.accepted, request], members: [...room.members, request] } })}><Ionicons name="checkmark-circle" size={28} color={colors.mint}/></Pressable><Pressable onPress={() => set({ room: { ...room, requests: room.requests.filter(item => item !== request) } })}><Ionicons name="close-circle" size={28} color={colors.danger}/></Pressable></View></View>)}{room.accepted.length > 0 && <View style={styles.route}><Text style={styles.routeText}>{room.accepted.join(', ')} accepted</Text><Text style={styles.secondaryText}>BLEND UPDATED</Text></View>}<FeatureButton label="Open capsule" onPress={() => set({ screen: 'feature', featureMode: 'capsule' })} secondary/></ScrollView></SafeAreaView>; }
function CapsuleScreen() { const { capsule, set } = useApp(); const approve = (member: string) => set({ capsule: { ...capsule, approvals: { ...capsule.approvals, [member]: true } } }); return <SafeAreaView style={styles.safe}><FeatureHeader label="CAPSULE" onBack={() => set({ screen: 'feature', featureMode: 'joinRequests' })}/><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>SHUFFL CAPSULE</Text><Text style={styles.title}>A smaller circle inside the room</Text><Text style={styles.body}>Everyone approves before the capsule request reaches the host. Exact locations stay hidden until the room consent state allows them.</Text>{capsule.members.map(member => <View key={member} style={styles.route}><View><Text style={styles.routeText}>{member}</Text><Text style={styles.secondaryText}>{capsule.approvals[member] ? 'APPROVED' : 'WAITING FOR APPROVAL'}</Text></View>{!capsule.approvals[member] && <Pressable onPress={() => approve(member)}><Ionicons name="checkmark-circle-outline" size={28} color={colors.mint}/></Pressable>}</View>)}<FeatureButton label={capsule.members.every(member => capsule.approvals[member]) ? 'Request to join room' : 'Waiting for capsule approval'} onPress={() => set({ screen: 'feature', featureMode: 'notifications' })}/></ScrollView></SafeAreaView>; }
function ChatScreen() { const { set } = useApp(); const [sent, setSent] = useState(false); return <SafeAreaView style={styles.safe}><FeatureHeader label="GROUP CHAT" onBack={() => set({ screen: 'feature', featureMode: 'inbox' })}/><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>FRIDAY ROOM</Text><Text style={styles.title}>Talk through the night</Text><View style={styles.route}><Text style={styles.routeText}>Aarav</Text><Text style={styles.secondaryText}>Should we start at Sidecar?</Text></View><View style={styles.route}><Text style={styles.routeText}>Bela</Text><Text style={styles.secondaryText}>The plan is in. I’m in for the first stop.</Text></View>{sent && <View style={styles.route}><Text style={styles.routeText}>You</Text><Text style={styles.secondaryText}>I’ll share arrival details privately.</Text></View>}<FeatureButton label={sent ? 'Message sent' : 'Send arrival message'} onPress={() => setSent(true)}/><FeatureButton label="View active plan" onPress={() => set({ screen: 'feature', featureMode: 'activePlan' })} secondary/></ScrollView></SafeAreaView>; }

export function FeatureScreen({ mode }: { mode: FeatureMode }) {
  if (mode === 'hostRoom') return <HostRoomScreen/>;
  if (mode === 'activePlan') return <ActivePlanScreen/>;
  if (mode === 'joinRequests') return <JoinRequestsScreen/>;
  if (mode === 'capsule') return <CapsuleScreen/>;
  if (mode === 'chat') return <ChatScreen/>;
  const { set } = useApp(); const item = content[mode];
  const go = () => item.next ? set({ screen: 'feature', featureMode: item.next }) : set({ screen: 'profileHome' });
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => set({ screen: 'control' })} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.text}/></Pressable><Text style={styles.headerLabel}>{item.eyebrow}</Text><Ionicons name={item.icon} size={22} color={colors.mint}/></View><ScrollView contentContainerStyle={styles.content}><View style={styles.heroIcon}><Ionicons name={item.icon} size={34} color={colors.mint}/></View><Text style={styles.eyebrow}>{item.eyebrow}</Text><Text style={styles.title}>{item.title}</Text><Text style={styles.body}>{item.body}</Text><Pressable onPress={go} style={styles.primary}><Text style={styles.primaryText}>{item.action}</Text></Pressable>{mode==='settings'&&<View style={styles.routeList}>{(Object.keys(content) as FeatureMode[]).map((route)=><Pressable key={route} onPress={()=>set({screen:'feature',featureMode:route})} style={styles.route}><Text style={styles.routeText}>{content[route].eyebrow}</Text><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable>)}</View>}<Pressable onPress={() => set({ screen: 'feature', featureMode: 'settings' })} style={styles.secondary}><Text style={styles.secondaryText}>Open feature hub</Text></Pressable></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},header:{height:76,paddingHorizontal:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:44,height:44,alignItems:'center',justifyContent:'center'},headerLabel:{color:colors.muted,fontSize:12,letterSpacing:1.3},content:{padding:20,paddingBottom:100},heroIcon:{width:72,height:72,borderRadius:24,backgroundColor:'#12332D',alignItems:'center',justifyContent:'center',marginBottom:24},eyebrow:{color:colors.mint,fontSize:11,letterSpacing:1.7,fontWeight:'800',marginBottom:12},title:{color:colors.text,fontSize:34,lineHeight:40,fontWeight:'800',marginBottom:14},body:{color:colors.muted,fontSize:16,lineHeight:24,marginBottom:24},primary:{minHeight:54,borderRadius:16,backgroundColor:colors.mint,alignItems:'center',justifyContent:'center',marginTop:8},primaryText:{color:colors.bg,fontWeight:'800',fontSize:15},routeList:{marginTop:18,borderTopWidth:1,borderTopColor:colors.line},route:{minHeight:50,borderBottomWidth:1,borderBottomColor:colors.line,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},routeText:{color:colors.text,fontSize:13,fontWeight:'700',letterSpacing:.5},secondary:{minHeight:54,borderRadius:16,backgroundColor:colors.raised,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center',marginTop:12},secondaryText:{color:colors.text,fontWeight:'700',fontSize:15}});
