import { create } from 'zustand';
import { Action } from './algorithms';
import { Factor } from './data';
import { AssessmentState, createAssessment, createPreferences, PreferenceState } from './fullEngine';
export type FeatureMode='venue'|'activePlan'|'arrival'|'feedback'|'hostRoom'|'joinRequests'|'capsule'|'notifications'|'inbox'|'chat'|'visitor'|'editProfile'|'history'|'privacy'|'settings'|'report'|'support';
export type DemoRoomState={name:string; public:boolean; cohosts:string[]; members:string[]; requests:string[]; accepted:string[]};
export type DemoPlanState={exists:boolean; locked:boolean; style:string; stops:string[]};
export type DemoCapsuleState={members:string[]; approvals:Record<string,boolean>};
type Screen='welcome'|'intro'|'login'|'profile'|'preferences'|'instructions'|'assessment'|'reveal'|'discover'|'search'|'plans'|'rooms'|'profileHome'|'control'|'feature';
type State={screen:Screen; featureMode:FeatureMode; assessmentIndex:number; scores:Partial<Record<Factor,number>>; actions:Record<string,Action>; assessment:AssessmentState; preferences:PreferenceState; room:DemoRoomState; plan:DemoPlanState; capsule:DemoCapsuleState; locked:boolean; userName:string; set:(p:Partial<State>)=>void; reset:()=>void};
const initialRoom=():DemoRoomState=>({name:"Aarav’s Friday Room",public:false,cohosts:[],members:['Aarav'],requests:['Riya'],accepted:[]});
const initialPlan=():DemoPlanState=>({exists:false,locked:false,style:'Settle Then Roam',stops:['Sidecar · 8:30–10:10','Majnu ka Tila · 10:20–11:35','Sunder Nursery · 11:45–12:30']});
const initialCapsule=():DemoCapsuleState=>({members:['Bela','Chirag'],approvals:{Bela:false,Chirag:false}});
export const useApp= create<State>((set)=>({screen:'welcome',featureMode:'settings',assessmentIndex:0,scores:{},actions:{},assessment:createAssessment(),preferences:createPreferences(),room:initialRoom(),plan:initialPlan(),capsule:initialCapsule(),locked:true,userName:'Aarav',set:(p)=>set(p),reset:()=>set({screen:'welcome',featureMode:'settings',assessmentIndex:0,scores:{},actions:{},assessment:createAssessment(),preferences:createPreferences(),room:initialRoom(),plan:initialPlan(),capsule:initialCapsule(),locked:true})}));
